name: Workflow de CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Fazer checkout do código
      uses: actions/checkout@v3

    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14' 

    - name: Instalar dependências
      run: |
        cd website-vuejs
        npm install

    - name: Rodar os testes
      run: |
        cd website-vuejs/cucumber/hospedado/
        npx cucumber-js  # Rodar os testes de aceitação no site hospedado
        cd ../local/
        npx cucumber-js  # Rodar os testes de aceitação local
        cd ../..
        npm run jest  # Rodar os testes de caracterização com Jest
