name: CI Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Fazer checkout do código
      uses: actions/checkout@v3

    - name: Configurar Node.js versão 14
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Instalar dependências
      run: |
        cd website-vuejs
        npm install

    - name: Rodar os testes de caracterização
      run: |
        cd website-vuejs
        npm run jest