name: CI Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Fazer checkout do código
      uses: actions/checkout@v3

    - name: Instalar nvm (Node Version Manager)
      run: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
        source ~/.bashrc
        nvm install 14  # Instalar a versão 14 do Node.js
        nvm use 14

    - name: Instalar dependências
      run: |
        cd website-vuejs
        npm install

    - name: Rodar os testes
      run: |
        cd website-vuejs/cucumber/hospedado/
        npx cucumber-js  # Testes de aceitação hospedado
        cd ../local/
        npx cucumber-js  # Testes de aceitação local
        cd ../..
        npm run jest  # Testes de caracterização
