name: Workflow de CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Fazer checkout do código
      uses: actions/checkout@v3

    - name: Configurar Node.js versão 14
      uses: actions/setup-node@v3
      with:
        node-version: '14'  

    - name: Instalar dependências
      run: |
        cd website-vuejs
        npm install

    - name: Rodar os testes de caracterização
      run: |
        cd website-vuejs
        npm run jest  

    - name: Configurar Node.js versão 20 para Cucumber
      uses: actions/setup-node@v3
      with:
        node-version: '20' 

    - name: Rodar os testes de aceitação (Cucumber)
      run: |
        cd website-vuejs/cucumber/hospedado/
        npx cucumber-js  # Rodar os testes de aceitação no site hospedado
        cd ../local/
        npx cucumber-js  # Rodar os testes de aceitação local